### PR TITLE
[WRKLDS-730] refactor route controller manager to use library-go server and ControlerCommand for generic setup 

### PR DESCRIPTION
**Pull request by atiratree**
Revert of https://github.com/openshift/route-controller-manager/pull/25. The hypershift failures should be resolved by merging  https://github.com/openshift/hypershift/pull/2674 first. EDIT: seems we have a circular dependency https://github.com/openshift/hypershift/pull/2674#issuecomment-1587241730 and these 2 PRs need to be merged at the same time.

- simplify ControllerContext.

TODO:

- [x] https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/295
- [x] https://github.com/openshift/hypershift/pull/2674
- [x] https://github.com/openshift/route-controller-manager/pull/29
- [x] https://github.com/openshift/hypershift/pull/2873

### CODE REVIEW

**Comment by ingvagabund** [comment]
`oc adm inspect returned an error`. I wonder whether that's the reason why the CI job fails.

**Comment by atiratree** [comment]
seems route-controller-manager is unable to become ready:

```
    create_cluster_test.go:293: condition Degraded status [True] doesn't match the expected status [False]
    create_cluster_test.go:304: Failed to validate HostedCluster conditions in 10m0s: timed out waiting for the condition
```

```
 - lastTransitionTime: "2023-08-02T11:52:43Z"
    message: openshift-route-controller-manager deployment has 1 unavailable replicas
    observedGeneration: 4
    reason: UnavailableReplicas
    status: "True"
    type: Degraded
```


```
  - lastProbeTime: null
    lastTransitionTime: "2023-08-02T11:52:54Z"
    message: 'containers with unready status: [route-controller-manager]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
```


```
 - containerID: cri-o://8f02b9f64dd545a0722b13cc4b91e2388fa50c4b26d8cc29c01194fb3b7b7023
    image: registry.build05.ci.openshift.org/ci-op-nljvl9tw/stable@sha256:67fe8c17f8e62f44ffba1215458f9a894f68f60d12b23c91a4ef06d6208131ce
    imageID: registry.build05.ci.openshift.org/ci-op-nljvl9tw/stable@sha256:67fe8c17f8e62f44ffba1215458f9a894f68f60d12b23c91a4ef06d6208131ce
    lastState: {}
    name: route-controller-manager
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-02T11:53:08Z"
```

not sure why, investigating...

**Comment by atiratree** [comment]
seems we need to update readiness paths in hypershift first: https://github.com/openshift/hypershift/pull/2873

**Comment by atiratree** [comment]
tests passed
/hold cancel

**Pull request merged**
